name: smart_campus_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # State Management
  flutter_riverpod: ^3.0.0
  
  # HTTP Calls
  dio: ^5.4.0

  # Local Database
  sqflite: ^2.3.3
  path: ^1.9.0

  # Save Token (stay logged in)
  shared_preferences: ^2.3.0

  # Calendar
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.0

  integration_test:
    sdk: flutter
  
flutter:
  uses-material-design: true