// Mocks generated by Mockito 5.4.6 from annotations
// in smart_campus_app/test/unit_test/booking_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_campus_app/features/bookings/data/booking_local_data_source.dart'
    as _i2;
import 'package:smart_campus_app/features/bookings/domain/models/booking_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BookingLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingLocalDataSource extends _i1.Mock
    implements _i2.BookingLocalDataSource {
  MockBookingLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BookingModel>> getAllBookings(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBookings, [userId]),
            returnValue: _i3.Future<List<_i4.BookingModel>>.value(
              <_i4.BookingModel>[],
            ),
          )
          as _i3.Future<List<_i4.BookingModel>>);

  @override
  _i3.Future<void> insertBooking(_i4.BookingModel? booking) =>
      (super.noSuchMethod(
            Invocation.method(#insertBooking, [booking]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBooking(_i4.BookingModel? booking) =>
      (super.noSuchMethod(
            Invocation.method(#updateBooking, [booking]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBooking(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBooking, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
