// Mocks generated by Mockito 5.4.6 from annotations
// in smart_campus_app/test/unit_test/facility_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_campus_app/features/facilities/data/facility_local_data_source.dart'
    as _i3;
import 'package:smart_campus_app/features/facilities/data/facility_remote_data_source.dart'
    as _i5;
import 'package:smart_campus_app/features/facilities/domain/models/facility_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFacilityModel_0 extends _i1.SmartFake implements _i2.FacilityModel {
  _FakeFacilityModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FacilityLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFacilityLocalDataSource extends _i1.Mock
    implements _i3.FacilityLocalDataSource {
  MockFacilityLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.FacilityModel>> getAllFacilities() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFacilities, []),
            returnValue: _i4.Future<List<_i2.FacilityModel>>.value(
              <_i2.FacilityModel>[],
            ),
          )
          as _i4.Future<List<_i2.FacilityModel>>);

  @override
  _i4.Future<_i2.FacilityModel?> getFacilityById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilityById, [id]),
            returnValue: _i4.Future<_i2.FacilityModel?>.value(),
          )
          as _i4.Future<_i2.FacilityModel?>);

  @override
  _i4.Future<void> insertFacility(_i2.FacilityModel? facility) =>
      (super.noSuchMethod(
            Invocation.method(#insertFacility, [facility]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateFacility(_i2.FacilityModel? facility) =>
      (super.noSuchMethod(
            Invocation.method(#updateFacility, [facility]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFacility(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFacility, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [FacilityRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFacilityRemoteDataSource extends _i1.Mock
    implements _i5.FacilityRemoteDataSource {
  MockFacilityRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.FacilityModel>> getAllFacilities() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFacilities, []),
            returnValue: _i4.Future<List<_i2.FacilityModel>>.value(
              <_i2.FacilityModel>[],
            ),
          )
          as _i4.Future<List<_i2.FacilityModel>>);

  @override
  _i4.Future<_i2.FacilityModel> getFacilityById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilityById, [id]),
            returnValue: _i4.Future<_i2.FacilityModel>.value(
              _FakeFacilityModel_0(
                this,
                Invocation.method(#getFacilityById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.FacilityModel>);

  @override
  _i4.Future<void> addFacility(_i2.FacilityModel? facility) =>
      (super.noSuchMethod(
            Invocation.method(#addFacility, [facility]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateFacility(_i2.FacilityModel? facility) =>
      (super.noSuchMethod(
            Invocation.method(#updateFacility, [facility]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFacility(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFacility, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
